//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:8</p>
  /// </summary>
  public class CoRiderModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<int> Port => _Port;
    [NotNull] public ISignal<JetBrains.Rider.Model.ServerStatus> ServerStatus => _ServerStatus;
    
    //private fields
    [NotNull] private readonly RdProperty<int> _Port;
    [NotNull] private readonly RdSignal<JetBrains.Rider.Model.ServerStatus> _ServerStatus;
    
    //primary constructor
    private CoRiderModel(
      [NotNull] RdProperty<int> port,
      [NotNull] RdSignal<JetBrains.Rider.Model.ServerStatus> serverStatus
    )
    {
      if (port == null) throw new ArgumentNullException("port");
      if (serverStatus == null) throw new ArgumentNullException("serverStatus");
      
      _Port = port;
      _ServerStatus = serverStatus;
      _Port.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("port", _Port));
      BindableChildren.Add(new KeyValuePair<string, object>("serverStatus", _ServerStatus));
    }
    //secondary constructor
    internal CoRiderModel (
    ) : this (
      new RdProperty<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdSignal<JetBrains.Rider.Model.ServerStatus>(JetBrains.Rider.Model.ServerStatus.Read, JetBrains.Rider.Model.ServerStatus.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -5530726814228802747L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("CoRiderModel (");
      using (printer.IndentCookie()) {
        printer.Print("port = "); _Port.PrintEx(printer); printer.Println();
        printer.Print("serverStatus = "); _ServerStatus.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionCoRiderModelEx
   {
    public static CoRiderModel GetCoRiderModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("coRiderModel", () => new CoRiderModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:10</p>
  /// </summary>
  public sealed class ServerStatus : IPrintable, IEquatable<ServerStatus>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    public int Port {get; private set;}
    [NotNull] public string Message {get; private set;}
    
    //private fields
    //primary constructor
    public ServerStatus(
      bool success,
      int port,
      [NotNull] string message
    )
    {
      if (message == null) throw new ArgumentNullException("message");
      
      Success = success;
      Port = port;
      Message = message;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, out int port, [NotNull] out string message)
    {
      success = Success;
      port = Port;
      message = Message;
    }
    //statics
    
    public static CtxReadDelegate<ServerStatus> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var port = reader.ReadInt();
      var message = reader.ReadString();
      var _result = new ServerStatus(success, port, message);
      return _result;
    };
    
    public static CtxWriteDelegate<ServerStatus> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      writer.Write(value.Port);
      writer.Write(value.Message);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ServerStatus) obj);
    }
    public bool Equals(ServerStatus other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Port == other.Port && Message == other.Message;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + Port.GetHashCode();
        hash = hash * 31 + Message.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ServerStatus (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("port = "); Port.PrintEx(printer); printer.Println();
        printer.Print("message = "); Message.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
