//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:8</p>
  /// </summary>
  public class CoRiderModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<int> Port => _Port;
    [NotNull] public ISignal<JetBrains.Rider.Model.ServerStatus> ServerStatus => _ServerStatus;
    [NotNull] public void CompanionPluginStatus(CompanionPluginInfo value) => _CompanionPluginStatus.Fire(value);
    [NotNull] public ISource<Unit> InstallCompanionPlugin => _InstallCompanionPlugin;
    [NotNull] public ISource<Unit> BuildCompanionPlugin => _BuildCompanionPlugin;
    [NotNull] public ISignal<string> McpConfigStatus => _McpConfigStatus;
    
    //private fields
    [NotNull] private readonly RdProperty<int> _Port;
    [NotNull] private readonly RdSignal<JetBrains.Rider.Model.ServerStatus> _ServerStatus;
    [NotNull] private readonly RdSignal<CompanionPluginInfo> _CompanionPluginStatus;
    [NotNull] private readonly RdSignal<Unit> _InstallCompanionPlugin;
    [NotNull] private readonly RdSignal<Unit> _BuildCompanionPlugin;
    [NotNull] private readonly RdSignal<string> _McpConfigStatus;
    
    //primary constructor
    private CoRiderModel(
      [NotNull] RdProperty<int> port,
      [NotNull] RdSignal<JetBrains.Rider.Model.ServerStatus> serverStatus,
      [NotNull] RdSignal<CompanionPluginInfo> companionPluginStatus,
      [NotNull] RdSignal<Unit> installCompanionPlugin,
      [NotNull] RdSignal<Unit> buildCompanionPlugin,
      [NotNull] RdSignal<string> mcpConfigStatus
    )
    {
      if (port == null) throw new ArgumentNullException("port");
      if (serverStatus == null) throw new ArgumentNullException("serverStatus");
      if (companionPluginStatus == null) throw new ArgumentNullException("companionPluginStatus");
      if (installCompanionPlugin == null) throw new ArgumentNullException("installCompanionPlugin");
      if (buildCompanionPlugin == null) throw new ArgumentNullException("buildCompanionPlugin");
      if (mcpConfigStatus == null) throw new ArgumentNullException("mcpConfigStatus");
      
      _Port = port;
      _ServerStatus = serverStatus;
      _CompanionPluginStatus = companionPluginStatus;
      _InstallCompanionPlugin = installCompanionPlugin;
      _BuildCompanionPlugin = buildCompanionPlugin;
      _McpConfigStatus = mcpConfigStatus;
      _Port.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("port", _Port));
      BindableChildren.Add(new KeyValuePair<string, object>("serverStatus", _ServerStatus));
      BindableChildren.Add(new KeyValuePair<string, object>("companionPluginStatus", _CompanionPluginStatus));
      BindableChildren.Add(new KeyValuePair<string, object>("installCompanionPlugin", _InstallCompanionPlugin));
      BindableChildren.Add(new KeyValuePair<string, object>("buildCompanionPlugin", _BuildCompanionPlugin));
      BindableChildren.Add(new KeyValuePair<string, object>("mcpConfigStatus", _McpConfigStatus));
    }
    //secondary constructor
    internal CoRiderModel (
    ) : this (
      new RdProperty<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdSignal<JetBrains.Rider.Model.ServerStatus>(JetBrains.Rider.Model.ServerStatus.Read, JetBrains.Rider.Model.ServerStatus.Write),
      new RdSignal<CompanionPluginInfo>(CompanionPluginInfo.Read, CompanionPluginInfo.Write),
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdSignal<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -2434328902332654397L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("CoRiderModel (");
      using (printer.IndentCookie()) {
        printer.Print("port = "); _Port.PrintEx(printer); printer.Println();
        printer.Print("serverStatus = "); _ServerStatus.PrintEx(printer); printer.Println();
        printer.Print("companionPluginStatus = "); _CompanionPluginStatus.PrintEx(printer); printer.Println();
        printer.Print("installCompanionPlugin = "); _InstallCompanionPlugin.PrintEx(printer); printer.Println();
        printer.Print("buildCompanionPlugin = "); _BuildCompanionPlugin.PrintEx(printer); printer.Println();
        printer.Print("mcpConfigStatus = "); _McpConfigStatus.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionCoRiderModelEx
   {
    public static CoRiderModel GetCoRiderModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("coRiderModel", () => new CoRiderModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:23</p>
  /// </summary>
  public sealed class CompanionPluginInfo : IPrintable, IEquatable<CompanionPluginInfo>
  {
    //fields
    //public fields
    public CompanionPluginStatus Status {get; private set;}
    [NotNull] public string InstalledVersion {get; private set;}
    [NotNull] public string BundledVersion {get; private set;}
    [NotNull] public string Message {get; private set;}
    
    //private fields
    //primary constructor
    public CompanionPluginInfo(
      CompanionPluginStatus status,
      [NotNull] string installedVersion,
      [NotNull] string bundledVersion,
      [NotNull] string message
    )
    {
      if (installedVersion == null) throw new ArgumentNullException("installedVersion");
      if (bundledVersion == null) throw new ArgumentNullException("bundledVersion");
      if (message == null) throw new ArgumentNullException("message");
      
      Status = status;
      InstalledVersion = installedVersion;
      BundledVersion = bundledVersion;
      Message = message;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out CompanionPluginStatus status, [NotNull] out string installedVersion, [NotNull] out string bundledVersion, [NotNull] out string message)
    {
      status = Status;
      installedVersion = InstalledVersion;
      bundledVersion = BundledVersion;
      message = Message;
    }
    //statics
    
    public static CtxReadDelegate<CompanionPluginInfo> Read = (ctx, reader) => 
    {
      var status = (CompanionPluginStatus)reader.ReadInt();
      var installedVersion = reader.ReadString();
      var bundledVersion = reader.ReadString();
      var message = reader.ReadString();
      var _result = new CompanionPluginInfo(status, installedVersion, bundledVersion, message);
      return _result;
    };
    
    public static CtxWriteDelegate<CompanionPluginInfo> Write = (ctx, writer, value) => 
    {
      writer.Write((int)value.Status);
      writer.Write(value.InstalledVersion);
      writer.Write(value.BundledVersion);
      writer.Write(value.Message);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CompanionPluginInfo) obj);
    }
    public bool Equals(CompanionPluginInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Status == other.Status && InstalledVersion == other.InstalledVersion && BundledVersion == other.BundledVersion && Message == other.Message;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (int) Status;
        hash = hash * 31 + InstalledVersion.GetHashCode();
        hash = hash * 31 + BundledVersion.GetHashCode();
        hash = hash * 31 + Message.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CompanionPluginInfo (");
      using (printer.IndentCookie()) {
        printer.Print("status = "); Status.PrintEx(printer); printer.Println();
        printer.Print("installedVersion = "); InstalledVersion.PrintEx(printer); printer.Println();
        printer.Print("bundledVersion = "); BundledVersion.PrintEx(printer); printer.Println();
        printer.Print("message = "); Message.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:16</p>
  /// </summary>
  public enum CompanionPluginStatus {
    NotInstalled,
    Outdated,
    Installed,
    UpToDate
  }
  
  
  /// <summary>
  /// <p>Generated from: CoRiderModel.kt:10</p>
  /// </summary>
  public sealed class ServerStatus : IPrintable, IEquatable<ServerStatus>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    public int Port {get; private set;}
    [NotNull] public string Message {get; private set;}
    
    //private fields
    //primary constructor
    public ServerStatus(
      bool success,
      int port,
      [NotNull] string message
    )
    {
      if (message == null) throw new ArgumentNullException("message");
      
      Success = success;
      Port = port;
      Message = message;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, out int port, [NotNull] out string message)
    {
      success = Success;
      port = Port;
      message = Message;
    }
    //statics
    
    public static CtxReadDelegate<ServerStatus> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var port = reader.ReadInt();
      var message = reader.ReadString();
      var _result = new ServerStatus(success, port, message);
      return _result;
    };
    
    public static CtxWriteDelegate<ServerStatus> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      writer.Write(value.Port);
      writer.Write(value.Message);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ServerStatus) obj);
    }
    public bool Equals(ServerStatus other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Port == other.Port && Message == other.Message;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + Port.GetHashCode();
        hash = hash * 31 + Message.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ServerStatus (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("port = "); Port.PrintEx(printer); printer.Println();
        printer.Print("message = "); Message.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
